[package]
name = "reqwest-json"
version = "0.1.0"
authors = ["Jason Poindexter <jason@launchbadge.com>"]

[dependencies]
reqwest = "0.8.0"
serde = "1.0.20"
serde_derive = "1.0.20"
serde_json = "1.0.6"